---
- hosts: localhost
  vars:
    infrared_hosts_dir: "{{ infrared_workspaces_dir }}/active"
    inventory_file_name: "hosts-updated"
  tasks:
    - include_tasks: tasks/get_interpreter.yml
      vars:
        hostname: "{{ undercloud_hostname }}"
        user: "stack"
    - name: add undercloud_host to inventory file
      add_host:
        name: "undercloud"
        groups: "baremetal,undercloud,tester"
        ansible_host: "{{ undercloud_hostname }}"
        ansible_user: "stack"
        ansible_ssh_private_key_file: "{{ ansible_ssh_key }}"
        ansible_python_interpreter: "{{ python_interpreter }}"

    - name: add localhost to inventory file
      add_host:
        name: "localhost"
        groups: "local"
        ansible_user: "root"
        ansible_python_interpreter: "{{ python_interpreter }}"

    - name: add freeipa_host to inventory file
      add_host:
        name: "freeipa"
        groups: "freeipa"
        ansible_host: "{{ freeipa_hostname }}"
        ansible_user: "root"
        ansible_ssh_private_key_file: "{{ ansible_ssh_key }}"
        ansible_python_interpreter: "{{ python_interpreter }}"
      when: tls_everywhere == true

    - name: generate inventory file
      template:
        dest: "{{ infrared_hosts_dir }}/{{ inventory_file_name }}"
        src: inventory.j2
    - name: update inventory file symlink
      file:
        dest: "{{ infrared_hosts_file }}"
        state: link
        src: "{{ inventory_file_name }}"
    - name: copy keys
      copy:
        src: "~/.ssh/id_rsa.pub"
        dest: "{{ infrared_hosts_dir }}/id_rsa_undercloud.pub"
