- hosts: undercloud
  become: yes
  become_user: stack
  vars:
      browbeat_dir: "/home/stack/browbeat"
  tasks:
    - name: clone browbeat
      git:
          repo: "https://github.com/cloud-bulldozer/browbeat.git"
          dest: "{{ browbeat_dir }}"
          force: yes
    - name: get dns server
      shell: |
          cat /etc/resolv.conf | grep nameserver | head -n1 | cut -d ' ' -f2
      register: dns_server
    - name: replace dns_server in groups vars
      shell: |
          sed -i 's/dns_server: 8.8.8.8/dns_server: {{ dns_server.stdout }}/g' {{ browbeat_dir }}/ansible/install/group_vars/all.yml
    - name: generate hosts file
      shell: |
          source /home/stack/stackrc
          ./generate_tripleo_hostfile.sh -l
      args:
          chdir: "{{ browbeat_dir }}/ansible"

    - name: Add OS_CACERT to overcloudrc
      lineinfile:
        path: overcloudrc
        insertafter: "export PYTHONWARNINGS"
        line: "export OS_CACERT=/etc/ipa/ca.crt"
      when: tls_everywhere == true

    - name: install browbeat
      shell: |
          ansible-playbook -i hosts install/browbeat.yml
      args:
          chdir: "{{ browbeat_dir }}/ansible"
    - name: Activate virtualenv to run tests
      shell: |
           source .browbeat-venv/bin/activate
      args:
          chdir: "{{ browbeat_dir }}"

