- hosts: localhost
  tasks:
      - name: install packages
        include_tasks: tasks/install_packages.yml

      - name: load instackenv file
        include_tasks: tasks/load_instackenv.yml

      - name: setup infrared
        include_tasks: tasks/setup_infrared.yml

      - name: add localhost to inventory file
        add_host:
          name: "localhost"
          groups: "local"
          ansible_connection: "local"

      - name: create a directory to store logs
        file:
          path: "{{ log_directory }}"
          state: directory
