---
- hosts: localhost
  roles:
    - { role: bootstrap, tags: [ undercloud, introspect, tag, composable, overcloud] }

- import_playbook: scale_compute_vms.yml
  when: scale_compute_vms == true

- import_playbook: setup_undercloud.yml
  tags:
    - undercloud
    - introspect
    - tag
    - composable
    - overcloud
  when: virtual_uc != true

- import_playbook: virtual_undercloud.yml
  tags:
    - undercloud
    - introspect
    - tag
    - composable
    - overcloud
  when: virtual_uc == true

- import_playbook: add_undercloud_to_inventory.yml
  tags:
    - undercloud
    - introspect
    - tag
    - composable
    - overcloud

- import_playbook: prepare_nic_configs.yml
  tags:
    - undercloud
    - introspect
    - tag
    - composable
    - overcloud
  when: composable_roles == false

- import_playbook: composable_prepare_nic_configs.yml
  tags:
    - undercloud
    - introspect
    - tag
    - composable
    - overcloud
  when: composable_roles

- import_playbook: undercloud.yml
  tags:
    - undercloud
- import_playbook: introspect.yml
  tags:
    - introspect

- import_playbook: tag.yml
  tags:
    - tag

- import_playbook: composable.yml
  tags:
    - composable
  when: composable_roles

- import_playbook: external.yml
  tags:
    - external
    - overcloud

- import_playbook: overcloud.yml
  tags:
    - overcloud

- import_playbook: post.yml
  tags:
    - post
    - overcloud

- import_playbook: ocp_on_osp.yml
  tags:
    - shift_stack
  when: shift_stack == true

- import_playbook: browbeat.yml
  tags:
    - browbeat
  when: browbeat is not defined or browbeat == true

- import_playbook: cleanup.yml
  tags:
    - cleanup
    - never
