- hosts: localhost
  tasks:
      - name: add undercloud_host to inventory file
        add_host:
            name: "{{ undercloud_hostname }}"
            ansible_user: "stack"
      - name: copy instack file to /home/stack/instackenv.json for infrared tagging
        copy:
            src: "{{ overcloud_instackenv_path }}"
            dest: "/home/stack/instackenv.json"
        delegate_to: "{{ groups.undercloud|first }}"

      - name: run tripleo-overcloud tagging
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --deployment-files {{ nic_configs }} --introspect no --tagging yes > {{ log_directory }}/overcloud_tagging.log 2&>1
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
