- hosts: localhost
  vars:
    container_params: ""
  tasks:
      - name: set undercloud local interface
        block:
          - name: get undercloud_local_interface
            shell: |
              for i in /sys/class/net/*
              do
                udevcontent=`udevadm info -p $i --query property`
                if [[ $udevcontent =~ {{ uc_ctlplane_interface }} ]]
                then
                  undercloud_local_interface=`echo $i | cut -d '/' -f 5`
                  break
                fi
              done
              echo $undercloud_local_interface
            register: local_interface
            delegate_to: "{{ undercloud_hostname }}"
            vars:
              uc_ctlplane_interface: "{{ (composable_roles == false) | ternary(ctlplane_interface, ctlplane_interfaces[0]) }}"
              ansible_python_interpreter: "{{ python_interpreter }}"
              ansible_user: "stack"
            become: true
            when: lab_name in ['scale', 'alias']

          - name: set undercloud_local_interface
            set_fact:
              undercloud_local_interface: "{{ local_interface.stdout }}"
          - debug:
              msg: "{{ undercloud_local_interface }}"
        when: virtual_uc != true

      - name: set undercloud_local_interface
        set_fact:
          undercloud_local_interface: "{{ undercloud_local_interface }}"
        when: (virtual_uc == true) or (lab_name not in ['scale', 'alias'])

      - name: Setup undercloud.conf
        template:
            src: undercloud.conf.j2
            dest: "{{ undercloud_conf }}"
      - name: Set container params
        set_fact:
          container_params: "--registry-mirror {{ registry_mirror }} --registry-namespace {{ registry_namespace }}"
        when: osp_release > 13
      - name: run tripleo-undercloud
        shell: |
          source {{ infrared_dir }}/.venv/bin/activate
          infrared tripleo-undercloud -vv \
          --version {{ osp_release }} \
          --build {{ osp_puddle }} \
          --images-task rpm \
          --config-file {{ undercloud_conf }} {{ container_params }} > {{ log_directory }}/undercloud_install.log 2>&1
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
