---
- name: Clear redfish job queues
  shell: |
    source {{ badfish_venv }}/bin/activate;
    python3 badfish.py -H mgmt-{{ item[1].stdout }}  -u quads -p {{ chassis_password }} --clear-jobs --force
  args:
    chdir: "{{ ansible_user_dir }}/badfish/src/badfish"
  when: vendors is defined and item[0] == "dell"
  with_together:
    - "{{ vendors }}"
    - "{{ host_list.results }}"
  register: clear_jobs
  until: clear_jobs is succeeded
  retries: 3
  delay: 30

- name: Wait for iDrac to be responsive
  shell: |
    source {{ badfish_venv }}/bin/activate;
    python3 badfish.py -H mgmt-{{ item[1].stdout }}  -u quads -p {{ chassis_password }} -i "{{ ansible_user_dir }}/badfish/config/idrac_interfaces.yml" --check-boot
  args:
    chdir: "{{ ansible_user_dir }}/badfish/src/badfish"
  when: vendors is defined and item[0] == "dell"
  with_together:
    - "{{ vendors }}"
    - "{{ host_list.results }}"
  register: wait_for_idrac
  until: wait_for_idrac is succeeded
  retries: 20
  delay: 30

- name: set boot order director (badfish)
  shell: |
    source {{ badfish_venv }}/bin/activate;
    python3 badfish.py -H mgmt-{{ item[1].stdout }}  -u quads -p {{ chassis_password }} -i "{{ ansible_user_dir }}/badfish/config/idrac_interfaces.yml" -t director
  args:
    chdir: "{{ ansible_user_dir }}/badfish/src/badfish"
  when: vendors is defined and item[0] == "dell"
  with_together:
    - "{{ vendors }}"
    - "{{ host_list.results }}"
  retries: 5
  delay: 3
  register: result
  until: result.rc == 0

- name: power cycle overcloud nodes
  shell:
    source {{ badfish_venv }}/bin/activate;
    python3 badfish.py -H mgmt-{{ item[1].stdout }}  -u quads -p {{ chassis_password }} --power-cycle
  args:
    chdir: "{{ ansible_user_dir }}/badfish/src/badfish"
  when: vendors is defined and item[0] == "dell"
  with_together:
    - "{{ vendors }}"
    - "{{ host_list.results }}"

- name: Wait for iDrac to be responsive
  shell: |
    source {{ badfish_venv }}/bin/activate;
    python3 badfish.py -H mgmt-{{ item[1].stdout }}  -u quads -p {{ chassis_password }} -i "{{ ansible_user_dir }}/badfish/config/idrac_interfaces.yml" --check-boot
  args:
    chdir: "{{ ansible_user_dir }}/badfish/src/badfish"
  when: vendors is defined and item[0] == "dell"
  with_together:
    - "{{ vendors }}"
    - "{{ host_list.results }}"
  register: wait_for_idrac
  until: wait_for_idrac is succeeded
  retries: 20
  delay: 30
